version: '3'

services:
  nacos:
    image: nacos/nacos-server:v2.2.3
    container_name: nacos-quickstart
    ports:
      - 8848:8848
      - 9848:9848
      - 9849:9849
    environment:
      MODE: standalone